#!/usr/bin/env python3
import requests 
from pprint import pprint
import time
import json

class APIWeather(object):
	"""docstring for APIWeather"""
	def __init__(self, longi, latt):
				#Key generated by the api to call
		self.apiKey = "5848ff07bb54b0148626562ffda70065"
		#Getting data from RTK Class
		self.lat = latt
		self.lon = longi
		self.url = 'http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&appid={}&units=metric'.format(self.lat,self.lon,self.apiKey)
		res = requests.get(self.url)
		self.lastData = res.json()
		self.lastTime = time.time()
		self.secIntervall = 600 #600 seconds between each api call

	def strAll(self):
		print(self.url + "\n " + str(self.lastData) + "\n" + str(self.lastTime)) 

	def isAPIRested(self):
		curTime = time.time()
		if curTime > self.lastTime+self.secIntervall :
			self.lastTime = curTime
			return 1
		else: 
			return 0

	def callAPI(self):
		res = requests.get(self.url)
		dataB = res.json()
		return dataB

	def getWeather(self):
		if self.isAPIRested() == 1:
			print("rested")
			data = self.callAPI()
			print(data['weather'][0]['description'])
			return data['weather'][0]['description']
		else:
			data = self.lastData
			print("noRest")
			print(data['weather'][0]['description'])
			return data['weather'][0]['description']

	def getTemperature(self):
		if self.isAPIRested() == 1:
			print("rested")
			data = self.callAPI()
			print(data['main']['temp'])
			return data['main']['temp']
		else:
			data = self.lastData
			print("noRest")
			print(data['main']['temp'])
			return data['main']['temp']

	def getHumidity(self):
		if self.isAPIRested() == 1:
			print("rested")
			data = self.callAPI()
			print(data['main']['humidity'])
			return data['main']['humidity']
		else:
			data = self.lastData
			print("noRest")
			print(data['main']['humidity'])
			return data['main']['humidity']

